# Generated by Django 4.2.7 on 2023-12-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Contact_Number', models.IntegerField(blank=True, max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=50)),
                ('Address', models.CharField(blank=True, max_length=50)),
                ('Gender', models.CharField(blank=True, max_length=50)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
