# Generated by Django 4.2.7 on 2023-12-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=65, null=True)),
                ('Product_ID', models.IntegerField(blank=True, max_length=65)),
                ('Product_Quantity', models.IntegerField(blank=True, max_length=65)),
            ],
        ),
    ]
