# Generated by Django 4.2.7 on 2023-12-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Category',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
