# Generated by Django 4.2.7 on 2023-12-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_employee_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.IntegerField(blank=True, max_length=65)),
                ('Order_Date', models.CharField(max_length=65, null=True)),
                ('Order_Shipping_Address', models.CharField(max_length=65, null=True)),
            ],
        ),
    ]
